@CncMeasurement.Web_HostAddress = http://localhost:5078


GET {{CncMeasurement.Web_HostAddress}}/MockEntry/
Accept: application/json

###

GET {{CncMeasurement.Web_HostAddress}}/ListSummaries/
Accept: application/json

###

GET {{CncMeasurement.Web_HostAddress}}/ListDevices/
Accept: application/json

###

GET {{CncMeasurement.Web_HostAddress}}/RequestSingleMeasurement/
Accept: application/json