@CncMeasurement.Web_HostAddress = http://localhost:5078



GET {{CncMeasurement.Web_HostAddress}}/GetSampleRequest/
Accept: application/json

###

GET {{CncMeasurement.Web_HostAddress}}/RunExampleExperiment/
Accept: application/json